name: state_management_examples
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.3.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

